--- 
clone: 
  depth: 1
kind: pipeline
name : OldCam
version: Nexus-OLD
steps:
 - name: Nexus
   image: atomxorg/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh